//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetniLager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LagerEntities : DbContext
    {
        public LagerEntities()
            : base("name=LagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accounting> accounting { get; set; }
        public DbSet<Ddirection> Ddirection { get; set; }
        public DbSet<group> group { get; set; }
        public DbSet<specialty> specialty { get; set; }
        public DbSet<TtypeCompetition> TtypeCompetition { get; set; }
    }
}
